//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirstSmartPool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chlorine
    {
        public int ChlorineValueId { get; set; }
        public string MinimumFreeChlorine { get; set; }
        public string MaximumFreeChlorine { get; set; }
        public string MinimumBondedChlorine { get; set; }
        public string MaximumBondedChlorine { get; set; }
    
        public virtual ValueConstraints ValueConstraint { get; set; }
    }
}
