//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirstSmartPool
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonitorUnit
    {
        public int MonitorUnitId { get; set; }
        public int PoolPoolId { get; set; }
        public string SerialNo { get; set; }
    
        public virtual Pool Pool { get; set; }
    }
}
