//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirstSmartPool
{
    using System;
    using System.Collections.Generic;
    
    public partial class pH
    {
        public int pHValueId { get; set; }
        public string MinimumPhValue { get; set; }
        public string MaximumPhValue { get; set; }
    
        public virtual ValueConstraints ValueConstraint { get; set; }
    }
}
