

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Data.Entity.Validation;
using System.Linq;

namespace ModelFirstSmartPool
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class SmartPoolContext : DbContext
{
    public SmartPoolContext()
        : base("name=SmartPoolContext")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

        public override int SaveChanges()
        {
            try
            {
                return base.SaveChanges();
            }
            catch (DbEntityValidationException exception)
            {
                var errMsg = exception.EntityValidationErrors
                    .SelectMany(x => x.ValidationErrors)
                    .Select(x => x.ErrorMessage);

                var fullMsg = string.Join("; ", errMsg);

                var exceptionMsg = string.Concat(exception.Message, "The validation errors are: ", fullMsg);
                throw new DbEntityValidationException(exceptionMsg, exception.EntityValidationErrors);
            }
        }


        public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<Pool> Pools { get; set; }

    public virtual DbSet<FullName> FullNames { get; set; }

    public virtual DbSet<MonitorUnit> MonitorUnits { get; set; }

    public virtual DbSet<Residence> Residences { get; set; }

    public virtual DbSet<PoolDimensions> PoolDimensions { get; set; }

    public virtual DbSet<ValueConstraints> ValueConstraints { get; set; }

    public virtual DbSet<pH> pHs { get; set; }

    public virtual DbSet<Chlorine> ChlorineValues { get; set; }

}

}

