//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirstSmartPool
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValueConstraints
    {
        public int ValueConstraintsId { get; set; }
    
        public virtual pH pH { get; set; }
        public virtual Chlorine ChlorineConstraint { get; set; }
        public virtual Residence Residence { get; set; }
    }
}
