language: csharp
solution: ./Smartpool/Smartpool.sln

install:
  - sudo apt-get install nunit-console
  - nuget restore ./Smartpool/Smartpool.sln

script:
  - xbuild ./Smartpool/Smartpool.sln
  - nunit-console ./Smartpool/Database.Test.Unit/bin/Debug/Database.Test.Unit.dll
  - nunit-console ./Smartpool/Connection.Server.Test.Unit/bin/Debug/Connection.Server.Test.Unit.dll
  - nunit-console ./Smartpool/Application.Test.Unit/bin/Debug/Application.Test.Unit.dll