//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smartpool
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseContext : DbContext
    {
        public DatabaseContext()
            : base("name=DatabaseContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Pool> PoolSet { get; set; }
        public virtual DbSet<pH> pHSet { get; set; }
        public virtual DbSet<Chlorine> ChlorineSet { get; set; }
        public virtual DbSet<Temperature> TemperatureSet { get; set; }
        public virtual DbSet<Humidity> HumiditySet { get; set; }
        public virtual DbSet<Data> DataSet { get; set; }
    }
}
