// <auto-generated />
namespace SPDatabase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class testing1411 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testing1411));
        
        string IMigrationMetadata.Id
        {
            get { return "201603031338549_testing1411"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
