//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity.Validation;
using System.Linq;

namespace DBAccess_v1._0
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartPoolModelContainer : DbContext
    {
        public SmartPoolModelContainer()
            : base("name=SmartPoolModelContainer")
        {
        }

        public override int SaveChanges()
        {
            try
            {
                return base.SaveChanges();
            }
            catch (DbEntityValidationException exception)
            {
                var errMsg = exception.EntityValidationErrors
                    .SelectMany(x => x.ValidationErrors)
                    .Select(x => x.ErrorMessage);

                var fullMsg = string.Join("; ", errMsg);

                var exceptionMsg = string.Concat(exception.Message, "The validation errors are: ", fullMsg);
                throw new DbEntityValidationException(exceptionMsg, exception.EntityValidationErrors);
            }
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Pool> PoolSet { get; set; }
        public virtual DbSet<MonitorUnit> MonitorUnitSet { get; set; }
    }
}
